# cluster_config.yml - cluster configuration
__default__:
  time: 24:00:00
  nodes: 1
  ntasks_per_node: 1
  cpus_per_task: 6
  memory: 70G
  partition: comppriority
aln:
  time: 24:00:00
  nodes: 1
  ntasks_per_node: 1
  cpus_per_task: 12
  memory: 96G
  partition: comppriority
samse:
  time: 12:00:00
  nodes: 1
  ntasks_per_node: 1
  cpus_per_task: 1
  memory: 20G
  partition: comppriority
sam2bam:
  time: 6:00:00
  nodes: 1
  ntasks_per_node: 1
  cpus_per_task: 1
  memory: 20G
  partition: comppriority
sampe:
  time: 12:00:00
  nodes: 1
  ntasks_per_node: 1
  cpus_per_task: 1
  memory: 20G
  partition: comppriority
trim:
  time: 12:00:00
  nodes: 1
  ntasks_per_node: 1
  cpus_per_task: 6
  memory: 60G
  partition: comppriority
