ref: /maps/projects/lundbeck/data/hg38/genome.fa
seed: 32
a1: "AGATCGGAAGAGCACACGTCTGAACTCCAGTCAC"
a2: "GGAAGAGCGTCGTGTAGGGAAAGAGTGT"
units: units/units.tsv
outfol: /maps/projects/lundbeck/scratch/sslib_devel/mapped/
